package models

type Capability int

const (
	CAPABILITY_FETCH_UNKNOWN Capability = iota
	CAPABILITY_FETCH_ACCOUNTS
	CAPABILITY_FETCH_PAYMENTS
	CAPABILITY_FETCH_OTHERS
	CAPABILITY_WEBHOOKS
	CAPABILITY_CREATION_BANK_ACCOUNT
	CAPABILITY_CREATION_PAYMENT
)
