---
include:
  - .local/docker-compose.yml
services:
  gateway:
    image: "caddy:2.7.5-alpine"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ".local/gateway/Caddyfile:/etc/caddy/Caddyfile"

  ledger:
    image: "ghcr.io/formancehq/ledger:v2.0.0-beta.5"
    healthcheck:
      test: [ "CMD", "wget", "http://127.0.0.1:8080/_info", "-O", "-", "-q" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      STORAGE_DRIVER: "postgres"
      STORAGE_POSTGRES_CONN_STRING: "postgresql://formance:formance@postgres:${FORMANCE_POSTGRES_PORT:-5432}/ledger?sslmode=disable"

  payments-migrate:
    image: "ghcr.io/formancehq/payments:v1.0.0-rc.4"
    command: migrate up
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_URI: "postgres://formance:formance@postgres:${FORMANCE_POSTGRES_PORT:-5432}/payments?sslmode=disable"

  payments-api:
    image: "ghcr.io/formancehq/payments:v1.0.0-rc.4"
    command: api server
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:8080/_healthcheck" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
      payments-migrate:
        condition: service_completed_successfully
    environment:
      DEBUG: ${DEBUG:-"true"}
      POSTGRES_URI: "postgres://formance:formance@postgres:${FORMANCE_POSTGRES_PORT:-5432}/payments?sslmode=disable"
      CONFIG_ENCRYPTION_KEY: mysuperencryptionkey

  payments-connectors:
    image: "ghcr.io/formancehq/payments:v1.0.0-rc.4"
    command: connectors server
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:8080/_healthcheck" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
      payments-migrate:
        condition: service_completed_successfully
    environment:
      DEBUG: ${DEBUG:-"true"}
      POSTGRES_URI: "postgres://formance:formance@postgres:${FORMANCE_POSTGRES_PORT:-5432}/payments?sslmode=disable"
      CONFIG_ENCRYPTION_KEY: mysuperencryptionkey
