// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: workflow.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskTree struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NextTasks []*TaskTree `protobuf:"bytes,1,rep,name=next_tasks,json=nextTasks,proto3" json:"next_tasks,omitempty"`
	// Types that are assignable to Task:
	//
	//	*TaskTree_FetchAccounts_
	//	*TaskTree_FetchPayments_
	//	*TaskTree_FetchOthers_
	Task isTaskTree_Task `protobuf_oneof:"task"`
}

func (x *TaskTree) Reset() {
	*x = TaskTree{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workflow_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskTree) ProtoMessage() {}

func (x *TaskTree) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskTree.ProtoReflect.Descriptor instead.
func (*TaskTree) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *TaskTree) GetNextTasks() []*TaskTree {
	if x != nil {
		return x.NextTasks
	}
	return nil
}

func (m *TaskTree) GetTask() isTaskTree_Task {
	if m != nil {
		return m.Task
	}
	return nil
}

func (x *TaskTree) GetFetchAccounts() *TaskTree_FetchAccounts {
	if x, ok := x.GetTask().(*TaskTree_FetchAccounts_); ok {
		return x.FetchAccounts
	}
	return nil
}

func (x *TaskTree) GetFetchPayments() *TaskTree_FetchPayments {
	if x, ok := x.GetTask().(*TaskTree_FetchPayments_); ok {
		return x.FetchPayments
	}
	return nil
}

func (x *TaskTree) GetFetchOthers() *TaskTree_FetchOthers {
	if x, ok := x.GetTask().(*TaskTree_FetchOthers_); ok {
		return x.FetchOthers
	}
	return nil
}

type isTaskTree_Task interface {
	isTaskTree_Task()
}

type TaskTree_FetchAccounts_ struct {
	FetchAccounts *TaskTree_FetchAccounts `protobuf:"bytes,10,opt,name=fetch_accounts,json=fetchAccounts,proto3,oneof"`
}

type TaskTree_FetchPayments_ struct {
	FetchPayments *TaskTree_FetchPayments `protobuf:"bytes,11,opt,name=fetch_payments,json=fetchPayments,proto3,oneof"`
}

type TaskTree_FetchOthers_ struct {
	FetchOthers *TaskTree_FetchOthers `protobuf:"bytes,12,opt,name=fetch_others,json=fetchOthers,proto3,oneof"`
}

func (*TaskTree_FetchAccounts_) isTaskTree_Task() {}

func (*TaskTree_FetchPayments_) isTaskTree_Task() {}

func (*TaskTree_FetchOthers_) isTaskTree_Task() {}

type Workflow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tasks []*TaskTree `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
}

func (x *Workflow) Reset() {
	*x = Workflow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workflow_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Workflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workflow) ProtoMessage() {}

func (x *Workflow) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workflow.ProtoReflect.Descriptor instead.
func (*Workflow) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *Workflow) GetTasks() []*TaskTree {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type TaskTree_FetchAccounts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TaskTree_FetchAccounts) Reset() {
	*x = TaskTree_FetchAccounts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workflow_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskTree_FetchAccounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskTree_FetchAccounts) ProtoMessage() {}

func (x *TaskTree_FetchAccounts) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskTree_FetchAccounts.ProtoReflect.Descriptor instead.
func (*TaskTree_FetchAccounts) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{0, 0}
}

type TaskTree_FetchPayments struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TaskTree_FetchPayments) Reset() {
	*x = TaskTree_FetchPayments{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workflow_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskTree_FetchPayments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskTree_FetchPayments) ProtoMessage() {}

func (x *TaskTree_FetchPayments) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskTree_FetchPayments.ProtoReflect.Descriptor instead.
func (*TaskTree_FetchPayments) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{0, 1}
}

type TaskTree_FetchOthers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *TaskTree_FetchOthers) Reset() {
	*x = TaskTree_FetchOthers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workflow_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskTree_FetchOthers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskTree_FetchOthers) ProtoMessage() {}

func (x *TaskTree_FetchOthers) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskTree_FetchOthers.ProtoReflect.Descriptor instead.
func (*TaskTree_FetchOthers) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{0, 2}
}

func (x *TaskTree_FetchOthers) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_workflow_proto protoreflect.FileDescriptor

var file_workflow_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x1c, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb5,
	0x03, 0x0a, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x72, 0x65, 0x65, 0x12, 0x45, 0x0a, 0x0a, 0x6e,
	0x65, 0x78, 0x74, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x26, 0x2e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54,
	0x61, 0x73, 0x6b, 0x54, 0x72, 0x65, 0x65, 0x52, 0x09, 0x6e, 0x65, 0x78, 0x74, 0x54, 0x61, 0x73,
	0x6b, 0x73, 0x12, 0x5d, 0x0a, 0x0e, 0x66, 0x65, 0x74, 0x63, 0x68, 0x5f, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x72,
	0x65, 0x65, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73,
	0x48, 0x00, 0x52, 0x0d, 0x66, 0x65, 0x74, 0x63, 0x68, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x73, 0x12, 0x5d, 0x0a, 0x0e, 0x66, 0x65, 0x74, 0x63, 0x68, 0x5f, 0x70, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x66, 0x6f, 0x72, 0x6d,
	0x61, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x72, 0x65,
	0x65, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x48,
	0x00, 0x52, 0x0d, 0x66, 0x65, 0x74, 0x63, 0x68, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x12, 0x57, 0x0a, 0x0c, 0x66, 0x65, 0x74, 0x63, 0x68, 0x5f, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x73,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x63,
	0x65, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x72, 0x65, 0x65, 0x2e, 0x46,
	0x65, 0x74, 0x63, 0x68, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x73, 0x48, 0x00, 0x52, 0x0b, 0x66, 0x65,
	0x74, 0x63, 0x68, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x73, 0x1a, 0x0f, 0x0a, 0x0d, 0x46, 0x65, 0x74,
	0x63, 0x68, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x1a, 0x0f, 0x0a, 0x0d, 0x46, 0x65,
	0x74, 0x63, 0x68, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x21, 0x0a, 0x0b, 0x46,
	0x65, 0x74, 0x63, 0x68, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x06,
	0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x22, 0x48, 0x0a, 0x08, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c,
	0x6f, 0x77, 0x12, 0x3c, 0x0a, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x26, 0x2e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x72, 0x65, 0x65, 0x52, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73,
	0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66,
	0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x63, 0x65, 0x68, 0x71, 0x2f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x76, 0x33, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_workflow_proto_rawDescOnce sync.Once
	file_workflow_proto_rawDescData = file_workflow_proto_rawDesc
)

func file_workflow_proto_rawDescGZIP() []byte {
	file_workflow_proto_rawDescOnce.Do(func() {
		file_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(file_workflow_proto_rawDescData)
	})
	return file_workflow_proto_rawDescData
}

var file_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_workflow_proto_goTypes = []interface{}{
	(*TaskTree)(nil),               // 0: formance.payments.grpc.proto.TaskTree
	(*Workflow)(nil),               // 1: formance.payments.grpc.proto.Workflow
	(*TaskTree_FetchAccounts)(nil), // 2: formance.payments.grpc.proto.TaskTree.FetchAccounts
	(*TaskTree_FetchPayments)(nil), // 3: formance.payments.grpc.proto.TaskTree.FetchPayments
	(*TaskTree_FetchOthers)(nil),   // 4: formance.payments.grpc.proto.TaskTree.FetchOthers
}
var file_workflow_proto_depIdxs = []int32{
	0, // 0: formance.payments.grpc.proto.TaskTree.next_tasks:type_name -> formance.payments.grpc.proto.TaskTree
	2, // 1: formance.payments.grpc.proto.TaskTree.fetch_accounts:type_name -> formance.payments.grpc.proto.TaskTree.FetchAccounts
	3, // 2: formance.payments.grpc.proto.TaskTree.fetch_payments:type_name -> formance.payments.grpc.proto.TaskTree.FetchPayments
	4, // 3: formance.payments.grpc.proto.TaskTree.fetch_others:type_name -> formance.payments.grpc.proto.TaskTree.FetchOthers
	0, // 4: formance.payments.grpc.proto.Workflow.tasks:type_name -> formance.payments.grpc.proto.TaskTree
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_workflow_proto_init() }
func file_workflow_proto_init() {
	if File_workflow_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_workflow_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskTree); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workflow_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Workflow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workflow_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskTree_FetchAccounts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workflow_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskTree_FetchPayments); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workflow_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskTree_FetchOthers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_workflow_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*TaskTree_FetchAccounts_)(nil),
		(*TaskTree_FetchPayments_)(nil),
		(*TaskTree_FetchOthers_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_workflow_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workflow_proto_goTypes,
		DependencyIndexes: file_workflow_proto_depIdxs,
		MessageInfos:      file_workflow_proto_msgTypes,
	}.Build()
	File_workflow_proto = out.File
	file_workflow_proto_rawDesc = nil
	file_workflow_proto_goTypes = nil
	file_workflow_proto_depIdxs = nil
}
