project_name: ingester
includes:
  - from_file:
      path: ./../../.goreleaser.default.yaml
monorepo:
  tag_prefix: v
  dir: ./

builds:
  - binary: ingester
    id: ingester
    ldflags:
      - -X github.com/formancehq/ingester/cmd.BuildDate={{ .Date }}
      - -X github.com/formancehq/ingester/cmd.Version=v{{ .Version }}
      - -X github.com/formancehq/ingester/cmd.Commit={{ .ShortCommit }}
      - -extldflags "-static"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: "{{.ProjectName}}"
    builds:
      - ingester
    format: tar.gz
    name_template: "{{.ProjectName}}_{{.Os}}-{{.Arch}}"

release:
  prerelease: auto
  footer: |
    ## What to do next?
    - Read the [documentation](https://docs.formance.com/)
    - Join our [Slack server](https://formance.com/slack)