workflowVersion: 1.0.0
sources:
    my-source:
        inputs:
            - location: ${{ needs.get_openai_spec_url.outputs.openapi_spec_url }}
targets:
    php-default:
        target: php
        source: my-source
        publish:
            packagist:
                username: $PACKAGIST_USERNAME
                token: $PACKAGIST_TOKEN
