---
volumes:
  postgres_data:
services:
  postgres:
    platform: linux/x86_64
    image: "postgres:15-alpine"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ledger" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "${FORMANCE_POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: "formance"
      POSTGRES_PASSWORD: "formance"
      POSTGRES_MULTIPLE_DATABASES: "ledger,payments"
      PGDATA: "/data/postgres"
    volumes:
      - postgres_data:/data/postgres
      - ./postgres:/docker-entrypoint-initdb.d