version: 0.5

environment:
  - "OTEL_TRACES=true"
  - "OTEL_TRACES_EXPORTER=otlp"
  - "OTEL_TRACES_ENDPOINT=jaeger"
  - "OTEL_TRACES_PORT=4317"
  - "OTEL_TRACES_EXPORTER_OTLP_INSECURE=true"
  - "OTEL_TRACES_EXPORTER_OTLP_MODE=grpc"
  - "OTEL_TRACES_EXPORTER_OTLP_ENDPOINT=jaeger:4317"
  - "DEBUG=true"

processes:
  gateway:
    command: gateway run --config /etc/formance/gateway/Caddyfile --adapter caddyfile
    availability:
      restart: always
    environment:
      - "OTEL_SERVICE_NAME=gateway"
      - "OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317"
      - "OTEL_EXPORTER_OTLP_INSECURE=true"
      - "OTEL_EXPORTER_OTLP_PROTOCOL=grpc"

  ledger:
    command: ledger server start --storage.driver=postgres --storage.postgres.conn_string postgresql://formance:formance@postgres/ledger?sslmode=disable --server.http.bind_address 0.0.0.0:3068 --publisher-nats-enabled true --publisher-nats-url nats:4222 --publisher-topic-mapping *:ledger
    availability:
      restart: always
    environment:
      - "OTEL_SERVICE_NAME=ledger"

  wallets:
    command: wallets server --listen 0.0.0.0:8081 --stack-url http://localhost --stack-client-id wallets --stack-client-secret wallets
    availability:
      restart: always
    environment:
      - "OTEL_SERVICE_NAME=wallets"

  paymentsapi:
    command: payments api server --listen 0.0.0.0:8082 --publisher-nats-enabled true --publisher-nats-url nats:4222 --publisher-topic-mapping *:payments --postgres-uri postgresql://formance:formance@postgres/payments?sslmode=disable --config-encryption-key mysuperencryptionkey
    availability:
      restart: always
    environment:
      - "OTEL_SERVICE_NAME=paymentsapi"

  paymentsconnectors:
    command: payments connectors server --listen 0.0.0.0:8087 --publisher-nats-enabled true --publisher-nats-url nats:4222 --publisher-topic-mapping *:payments --postgres-uri postgresql://formance:formance@postgres/payments?sslmode=disable --config-encryption-key mysuperencryptionkey
    availability:
      restart: always
    environment:
      - "OTEL_SERVICE_NAME=paymentsconnectors"

  payments-migrate:
    command: payments migrate up --postgres-uri postgresql://formance:formance@postgres/payments?sslmode=disable
    availability:
      restart: never